### ISSUE TITLE
QWIIC Twist and Quad Relay not recognized - Updated

### ISSUE THREAD

**Issue by jpecor** [sparkfunX/SparkFun_ESP32_Thing_Plus_C#3]
I'm trying to use the Thing Plus C with a QWIIC Twist, and it does not recognize the device.  I have the Twist working with an RPi and Python library, so I know it functions.

I also tried the I2C scanner code from this repo, and the Twist is not seen on the bus.

Has the QWIIC interface been verified on this device?  Or is there something I should be doing differently?

**Comment by jpecor** [comment]
I have the same issue with the QWIIC Quad Relay, so it's not just isolated to the Twist.

**Comment by nseidle** [comment]
Are the power LEDs on the boards on? Are you doing anything with ESP32 pin 0? It controls the v-reg. It's pulled high by default (internal to the ESP32).

![image](https://user-images.githubusercontent.com/117102/157713911-edbb4a09-a3c8-4963-87b8-236d7826f5de.png)

Can you detect other I2C devices using the scanner?

**Comment by jpecor** [comment]
Yes, there is power to the Twist.  In fact, I ran the I2C scanner code, and it blinks the Twist LED, but there's no hit when it scans the addresses.

I haven't added other QWIIC boards to the chain to see if they are detected, yet.  I'll try that next.

**Comment by jpecor** [comment]
Just tried with a QWIIC 9DoF IMU and PIR.  Same result.
![ThingPlus_480x](https://user-images.githubusercontent.com/14111408/157722901-48e03f6d-99af-43aa-a376-31337d3f38e9.jpg)

**Comment by PaulZC** [comment]
Hi Jason,

Which version of ESP32 do you have installed? And do you have the ESP32 Dev Module selected?

Qwiic / Wire is working fine for me...

![image](https://user-images.githubusercontent.com/5690545/157725487-f1d6f1e4-f82f-473b-b4ea-c1ad928c75f7.png)

![image](https://user-images.githubusercontent.com/5690545/157725587-9e0d304a-4dce-4ae7-a140-dd8b0f9b95ed.png)

Best wishes,
Paul

**Comment by jpecor** [comment]
SHAZAM!!   I was not!  I was using the Adafruit ESP32 Feather based on the [instructions for the ESP32 Thing Plus.](https://learn.sparkfun.com/tutorials/esp32-thing-plus-hookup-guide?_ga=2.77818391.228739982.1646666499-2006893416.1610568867#software-setup)

Changing to the ESP32 Dev Module seems to be the ticket.  Or, at least, I see the devices with the scanner code.  

Now on to the intended application. If that works, I'll close this issue.  

Thanks for the help!

**Comment by jpecor** [comment]
That worked.  Thanks again!

**Comment by jpecor** [comment]
I am reopening this issue because I've run into a new wrinkle.  

Here's the situation:

- After switching the board to use the ESP32 Dev Module, the I2C Scanner sketch started working
- I switched back to my project setup, which is a Quad Relay and Twist, and it was working for those, as well.
- Then, we soldered header pins to the ESP32 C
- Post header attachment, I could no longer control the Twist/Relay - it doesn't see them there
- Additionally, if I have nothing connected to the QWIIC connector, the scanner tells me it's finding a device at 0x36

So, something changed post-header attachment.

Those through hole vias are *very* close to the ESP32 module CVs, and our concern was a possible solder bridge.  Everything looks very clean under the microscope.

Is it possible the proximity of the ESP32 module to the vias allowed some of the solder to flow under a CV and create an open on one of the module I/O?  

I can still program the device, so it's not flat-out broken.  But the I2C bus is not working correctly.

Any thoughts?  

Thanks!
Jason

**Comment by PaulZC** [comment]
Hi Jason,

The device at 0x36 is the MAX17048 battery fuel gauge. That suggests the I2C bus is still working correctly.

Are you still connecting via the 4-Pin Qwiic connector? Maybe try connecting via the SCL/SDA header pins instead?

Best wishes,
Paul

**Comment by jpecor** [comment]
Yes, I'm using the QWIIC connector.  I'll try the header pins next.  

Thanks for the Intel on the battery gauge.  Good to know!

**Comment by jpecor** [comment]
Direct connection to SDA/SCL works. Hmmm....  

Thanks @PaulZC !

**Comment by nseidle** [comment]
Sorry you're having so much trouble. Sounds like a bad Qwiic cable or bad connection. Continuity test the cable to see if it's bad. Also have a good look at the pins inside the Qwiic connector. It's rare but I've had an end pin bend sideways a few times.

Closing since it's not a hardware issue with the ESP32 Thing Plus C. Feel free to open more issues if you come across them.
