### ISSUE TITLE
Digital write to pin 18

### ISSUE THREAD

**Issue by Rubeanie** [sparkfunX/SparkFun_ESP32_Thing_Plus_C#4]
I am unable to write to digital pin 18 (sck)?
I am just trying as you would with any other pin, nothing fancy. Every other pin I'm using work.

**Comment by PaulZC** [comment]
Hello Ruben (@Rubeanie ),

The Thing Plus C is intentionally connected up differently to our other ESP32 Thing Plus boards - to provide access to all of the I/O pins. For the Thing Plus C we recommend installing Espressif's ESP32 board package and then selecting the _ESP32 Dev Module_ as the board. Once you have done that, SCK is digital pin 18.

Quick summary:
* Follow [Espressif's instructions ](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) to install the ESP32 board package
  * Add this line to your _Additional Board Manager URLs_ :
  * https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
  * (If you have more than one additional URL, separate them with commas)
* Once you have the ESP32 boards installed, from the _Tools_ menu, select _Board_ \ _ESP32 Arduino_ \ _ESP32 Dev Module_
  * (Do not select any of the other Dev Modules, or any of the SparkFun ESP32 boards)

For more information on which pin is which, please refer to [the schematic](https://cdn.sparkfun.com/assets/b/5/1/0/9/SparkFun_ESP32_Thing_Plus_C.pdf):

![image](https://user-images.githubusercontent.com/5690545/167805766-2d34595f-8c75-4918-be4e-765a7f678ee3.png)

![image](https://user-images.githubusercontent.com/5690545/167805916-21195e6d-ab98-4621-8252-9b6ee34b632e.png)

Best wishes,
Paul

**Comment by Rubeanie** [comment]
Sorry, that was a typo, I meant pin 18. I need to set it to 3v3 to run a stepper driver. All the other pins I'm using for it work aside from pin 18.
It's for the STEP pin on a DRV8825.

**Comment by PaulZC** [comment]
Hi @Rubeanie ,

This code produces a nice ~800kHz square wave on pin 18:

```
void setup() {
  pinMode(18, OUTPUT);
}

void loop() {
  digitalWrite(18, !digitalRead(18));
}
```

![image](https://user-images.githubusercontent.com/5690545/168033362-9da01f60-2add-4368-b605-b8afdce17f7a.png)

Please check the solder joint on pad 30. It is the one 0.05" 'North' of the 18/SCK breakout pad. Maybe you have a dry joint?

![image](https://user-images.githubusercontent.com/5690545/168035605-65a0f406-4747-4975-b823-ca048dd44329.png)

Best wishes,
Paul

**Comment by Rubeanie** [comment]
I set pin 18 to high, then checked all the pins with a multimeter. I found that pin 32 was high when trying to set pin 18. After finding this out, I tried setting pin 32 to high, and then pin 18 went high.
I don't think it's an issue with every board but for some reason, my pin 18 and 32 are swapped, it works fine now that I know this, it's just confusing.

**Comment by PaulZC** [comment]
Hi Ruben (@Rubeanie ),

Wow. How bizarre! I _think_ the only way that can happen is if the variant pins_arduino.h has been changed, or if you have the wrong board selected? Please check one last time that you have the latest ESP32 boards (v2.0.3) installed and that you have the _**ESP32 Dev Module**_ selected.

I'm going to close this issue, but please re-open it if you need more help with this.

Very best wishes,
Paul
